[project]
name = "mcp-a2a-master"
version = "0.1.0"
description = "在此處新增您的專案描述"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk>=0.2.15",
    "asyncclick>=8.1.8",
    "google-adk>=1.7.0",
    "mcp[cli]>=1.12.0",
]
